force-app/main/default/objects/FAAProcessStop__e/FAAProcessStop__e.object-meta.xml
<CustomObject>
    <label>FAAProcessStop</label>
    <pluralLabel>FAAProcessStops</pluralLabel>
</CustomObject>

force-app/main/default/objects/FAAProcessStop__e/fields/FraudProvider__c.field-meta.xml
<CustomField>
    <fullName>FraudProvider__c</fullName>
    <label>FraudProvider</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAAProcessStop__e/fields/FraudStatus__c.field-meta.xml
<CustomField>
    <fullName>FraudStatus__c</fullName>
    <label>FraudStatus</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAAProcessStop__e/fields/OrderSummaryId__c.field-meta.xml
<CustomField>
    <fullName>OrderSummaryId__c</fullName>
    <label>OrderSummaryId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAAProcessStop__e/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FAACallable.cls
public with sharing virtual class FAACallable implements Callable {


    // Dispatch actual methods
    public virtual Object call(String orderSummaryId, Map<String,Object> args) {
        return '';
    }


    public virtual void processComplete(List<String> orderSummaryIds, String status, String fraudProvider, String reason) {
        // Issue event FAAProcessComplete and update the OS with the status
        List<FAAProcessStop__e> faaProcessStopEventList = new List<FAAProcessStop__e>();
        for (String orderSummaryId : orderSummaryIds) {
            FAAProcessStop__e faaProcessStopEvent = new FAAProcessStop__e(
                orderSummaryId__c = orderSummaryId, 
                fraudStatus__c = status,
                fraudProvider__c = fraudProvider,
            	Reason__c = reason);
            faaProcessStopEventList.add(faaProcessStopEvent);
        }
        EventBus.publish(faaProcessStopEventList);
    }


}