force-app/main/default/objects/FAACheckLog__c/FAACheckLog__c.object-meta.xml
<CustomObject>
    <description>Record to provide and overview about the Fraud and Approval checks which have been perfomed</description>
    <label>FAACheckLog</label>
    <nameField>
        <label>FAACheckLog__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FAACheckLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FAACheckLog__c/fields/FraudProvider__c.field-meta.xml
<CustomField>
    <fullName>FraudProvider__c</fullName>
    <description>Indicates the name of the Fraud checks which is logged</description>
    <label>FraudProvider</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAACheckLog__c/fields/OrderSummaryId__c.field-meta.xml
<CustomField>
    <fullName>OrderSummaryId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Summary Id</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>FAACheckLogs</relationshipLabel>
    <relationshipName>FAACheckLogs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FAACheckLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the current Fraud Check</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/FAAFraudChecks__c.field-meta.xml
<CustomField>
    <fullName>FAAFraudChecks__c</fullName>
    <label>Fraud Checks</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FAACheck1</fullName>
            </value>
            <value>
                <fullName>FAACheck2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FAATriggerHelper.cls
public with sharing class FAATriggerHelper {
    public static final string STATUS_APPROVED = 'Approved';
    public static final string STATUS_PENDING = 'Pending';
    public static final string STATUS_REJECTED = 'Rejected';
    public static final string STATUS_MANUAL_REVIEW = 'Manual Review';
    public static final string STATUS_INITIATED = 'Initiated';

    /**
     * Provides the Order Summaries which have no pending check left
     */
    public static List<OrderSummary> getOrderSummariesToValidate(List <Id> orderSummaryIds) {

        List<FAACheckLog__c> pendingChecks = [SELECT ID, orderSummaryId__c, status__c, fraudProvider__c 
                                         FROM FAACheckLog__c 
                                         WHERE orderSummaryId__c 
                                         IN :orderSummaryIds
                                         AND status__c = :STATUS_PENDING];

        // Exclude pending checks
        for (FAACheckLog__c pendingCheck : pendingChecks) {
            if (orderSummaryIds.contains(pendingCheck.orderSummaryId__c)) {
                Integer index = orderSummaryIds.indexOf(pendingCheck.orderSummaryId__c);
                orderSummaryIds.remove(index);
            }
        }

        List<OrderSummary> orderSummaries = [SELECT ID, FAAFraudChecks__c 
                                            FROM OrderSummary 
                                            WHERE ID IN :orderSummaryIds];
        return orderSummaries;
    }

}